CREATE TABLE "TB_CLIENTE" (
	"ID"	INTEGER NOT NULL,
	"NOME"	TEXT NOT NULL,
	"ENDERECO"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);


CREATE TABLE "TB_VENDENDOR" (
	"ID"	INTEGER NOT NULL,
	"NOME"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);


CREATE TABLE "TB_PRODUTO" (
	"ID"	INTEGER NOT NULL,
	"NOME"	TEXT NOT NULL,
	"PRECO_UNIT"	REAL NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);


CREATE TABLE "TB_NOTAFISCAL" (
	"ID"	INTEGER NOT NULL,
	"SERIE"	INTEGER NOT NULL,
	"CLIENTE_ID"	INTEGER NOT NULL,
	"VENDEDOR_ID"	INTEGER NOT NULL,
	FOREIGN KEY("CLIENTE_ID") REFERENCES "TB_CLIENTE"("ID"),
	FOREIGN KEY("VENDEDOR_ID") REFERENCES "TB_VENDENDOR"("ID"),
	PRIMARY KEY("ID" AUTOINCREMENT)
);


CREATE TABLE "TB_ITEM_NOTAFISCAL" (
	"NOTAFISCAL_ID"	INTEGER NOT NULL,
	"PRODUTO_ID"	INTEGER NOT NULL,
	"QUANTIDADE"	INTEGER NOT NULL,
	"VALOR"	REAL NOT NULL,
	FOREIGN KEY("PRODUTO_ID") REFERENCES "TB_PRODUTO"("ID"),
	FOREIGN KEY("NOTAFISCAL_ID") REFERENCES "TB_NOTAFISCAL"("ID"),
	PRIMARY KEY("PRODUTO_ID","NOTAFISCAL_ID")
);